name: "CI" # Continuous Integration

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
  pull_request:
    branches: [main]
    paths:
      - 'backend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "^1.23"
      - name: Install dependencies
        run: cd backend && go mod download
      - name: Run linters (golangci-lint)
        uses: golangci/golangci-lint-action@v8.0.0
      - name: Run tests
        run: cd backend && go test ./...
